default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     10
  template: template0
  port: 5432
  username: zaprzemo
  password: zima

development:
  <<: *default
  database: collateral_manager_development

